version: "3.9"
services:
  001_banner:
    platform: linux/amd64
    build:
      context: ../../
      dockerfile: Dockerfile
    image: pbs-sample
    container_name: 001_banner
    privileged: true
    environment:
      JAVA_OPTS: "-Dspring.config.additional-location=/app/prebid-server/app.yaml"
    ports:
      - "8080:8080"
      - "8060:8060"
    volumes:
      - ./config.yaml:/app/prebid-server/app.yaml
      - ./file-settings.yaml:/sample/file-settings.yaml
      - ./stored_request.json:/sample/stored/stored_request.json
      - ./stored_response.json:/sample/stored/stored_response.json
