version: "3.9"
services:
  001_banner:
    platform: linux/amd64
    build:
      context: ../../
      dockerfile: Dockerfile
    image: pbs-sample
    container_name: 001_banner
    privileged: true
    environment:
      JAVA_OPTS: "-Dspring.config.additional-location=/app/prebid-server/app.yaml"
    ports:
      - "8080:8080"
      - "8060:8060"
    volumes:
      - ./configs/config.yaml:/app/prebid-server/app.yaml
      - ./configs/file-settings.yaml:/sample/file-settings.yaml
      - ./data/test-imp-id.json:/sample/stored/test-imp-id.json
      - ./data/test-bid-id.json:/sample/stored/test-bid-id.json
      - ./data/pbjs.html:/app/prebid-server/static/pbjs.html
