package org.prebid.server.functional.model.config.privacy

import com.fasterxml.jackson.annotation.JsonValue
import com.iab.gpp.encoder.field.UspNatV1Field

enum UsNationalPrivacySection {

    SHARING_NOTICE(UspNatV1Field.SHARING_NOTICE),
    SALE_OPT_OUT_NOTICE(UspNatV1Field.SALE_OPT_OUT_NOTICE),
    SHARING_OPT_OUT_NOTICE(UspNatV1Field.SHARING_OPT_OUT_NOTICE),
    TARGETED_ADVERTISING_OPT_OUT_NOTICE(UspNatV1Field.TARGETED_ADVERTISING_OPT_OUT_NOTICE),
    SENSITIVE_DATA_PROCESSING_OPT_OUT_NOTICE(UspNatV1Field.SENSITIVE_DATA_PROCESSING_OPT_OUT_NOTICE),
    SENSITIVE_DATA_LIMIT_USE_NOTICE(UspNatV1Field.SENSITIVE_DATA_LIMIT_USE_NOTICE),
    SALE_OPT_OUT(UspNatV1Field.SALE_OPT_OUT),
    SHARING_OPT_OUT(UspNatV1Field.SHARING_OPT_OUT),
    TARGETED_ADVERTISING_OPT_OUT(UspNatV1Field.TARGETED_ADVERTISING_OPT_OUT),
    SENSITIVE_DATA_RACIAL_ETHNIC_ORIGIN(UspNatV1Field.SENSITIVE_DATA_PROCESSING + 1),
    SENSITIVE_DATA_RELIGIOUS_BELIEFS(UspNatV1Field.SENSITIVE_DATA_PROCESSING + 2),
    SENSITIVE_DATA_HEALTH_INFO(UspNatV1Field.SENSITIVE_DATA_PROCESSING + 3),
    SENSITIVE_DATA_ORIENTATION(UspNatV1Field.SENSITIVE_DATA_PROCESSING + 4),
    SENSITIVE_DATA_CITIZENSHIP_STATUS(UspNatV1Field.SENSITIVE_DATA_PROCESSING + 5),
    SENSITIVE_DATA_GENETIC_ID(UspNatV1Field.SENSITIVE_DATA_PROCESSING + 6),
    SENSITIVE_DATA_BIOMETRIC_ID(UspNatV1Field.SENSITIVE_DATA_PROCESSING + 7),
    SENSITIVE_DATA_GEOLOCATION(UspNatV1Field.SENSITIVE_DATA_PROCESSING + 8),
    SENSITIVE_DATA_ID_NUMBERS(UspNatV1Field.SENSITIVE_DATA_PROCESSING + 9),
    SENSITIVE_DATA_ACCOUNT_INFO(UspNatV1Field.SENSITIVE_DATA_PROCESSING + 10),
    SENSITIVE_DATA_UNION_MEMBERSHIP(UspNatV1Field.SENSITIVE_DATA_PROCESSING + 11),
    SENSITIVE_DATA_COMMUNICATION_CONTENTS(UspNatV1Field.SENSITIVE_DATA_PROCESSING + 12),
    SENSITIVE_DATA_PROCESSING_ALL(UspNatV1Field.SENSITIVE_DATA_PROCESSING + "*"),
    CHILD_CONSENTS_FROM_13_TO_16(UspNatV1Field.KNOWN_CHILD_SENSITIVE_DATA_CONSENTS + 1),
    CHILD_CONSENTS_BELOW_13(UspNatV1Field.KNOWN_CHILD_SENSITIVE_DATA_CONSENTS + 2),
    PERSONAL_DATA_CONSENTS(UspNatV1Field.PERSONAL_DATA_CONSENTS),
    MSPA_COVERED_TRANSACTION(UspNatV1Field.MSPA_COVERED_TRANSACTION),
    MSPA_OPT_OUT_OPTION_MODE(UspNatV1Field.MSPA_OPT_OUT_OPTION_MODE),
    MSPA_SERVICE_PROVIDER_MODE(UspNatV1Field.MSPA_SERVICE_PROVIDER_MODE),
    GPC(UspNatV1Field.GPC);

    @JsonValue
    final String value

    private UsNationalPrivacySection(String value) {
        this.value = value
    }

    static UsNationalPrivacySection valueFromText(String value) {
        values().find { section -> section.value.equalsIgnoreCase(value) }
                ?: { throw new IllegalArgumentException("Invalid UsNationalPrivacySection value: $value") }()
    }
}
