version: "3.9"
services:
  001_banner:
    platform: linux/amd64
    build:
      context: ../
      dockerfile: Dockerfile
    image: pbs-sample
    container_name: 001_banner
    privileged: true
    environment:
      JAVA_OPTS: "-Dspring.config.additional-location=/app/prebid-server/app.yaml"
    ports:
      - "8000:8000"
      - "6060:6060"
    volumes:
      - ./prebid-config.yaml:/app/prebid-server/app.yaml
      - ./sample-app-settings.yaml:/sample/sample-app-settings.yaml
