version: "3.9"
services:
  001_banner:
    platform: linux/amd64
    build:
      context: ../
      dockerfile: Dockerfile
      args:
        - TEST=false
    image: pbs-sample
    container_name: 001_banner
    privileged: true
    ports:
      - "8000:8000"
      - "6060:6060"
    volumes:
      - /sample/prebid-config.yaml:/app/prebid-server/app.yaml
      - /sample/sample-app-settings.yaml:/sample/sample-app-settings.yaml
