name: check-style
on: [pull_request]

jobs:
  checkstyle_job:
    runs-on: ubuntu-latest
    name: Checkstyle job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Checkstyle (produce XML)
        id: checkstyle
        uses: nikitasavinov/checkstyle-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: 'github-pr-review'
          tool_name: 'checkstyle'
          checkstyle_config: checkstyle.xml
          checkstyle_version: 10.17.0
          level: 'error'
          fail_on_error: false
