name: reviewdog
on: [pull_request]

jobs:
  checkstyle:
    name: runner / checkstyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dbelyaev/action-checkstyle@v3
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          level: error
          checkstyle_config: checkstyle.xml
          fail_level: error
